include/freshports.php
(Google doesn’t like affiliate links without nofollow.)
=> Use nofollow on paid links

classes/port-display.php
Only show ONLY_FOR_ARCHS and NOT_FOR_ARCHS if they are not nil
Untested.
Should consider making this list of parameters a bulleted list or definition list, instead of paragraphs.
=> Hide blank ONLY_FOR_ARCHS and NOT_FOR_ARCHS

classes/searches.php
This allows one to get to the search form by just hitting tab once
instead of having to tab through many links before you get to the
search form. As far as I can tell, there is no other specific tab
order set and this seems much better than what was there previously.
As someone who likes to get to the search box quickly by using the keyboard, this helps a lot.
=> Add a tabindex into the search form.

include/freshports.php
These commits turn URLs in clickable links and also make problem reports accessible by one click.
=> Link URLs in commit messages

classes/port-display.php, include/freshports.php
These links are pointing to a page that indicates that portsmon.freebsd.org have been broken for two years (only the home page displays correctly).
Maybe it make sense to drop them now?
=> Remove PortsMon links

include/freshports.php, www/backend/index.php
Looks like feedvalidator.org doesn't work anymore, so this PR changes the validation service to the [W3C one](https://validator.w3.org/feed/) (which looks to use produce the same results as the [RSS Board validator](https://www.rssboard.org/rss-validator/), which says it uses the feedvalidator.org one, so it should in essence be the same as before.
=> RSS Validation Fixes

include/freshports.php, include/login.php, include/new-user.php, www/index.php, www/login.php, www/new-user.php, www/search.php
For the homepage, the `setfocus`-defining `script` tag is preceding the `DOCTYPE` definition, putting the document in quirks mode and preventing meaningful HTML validation.
This PR cleans up the usage of the `setfocus()` function pattern.
Rather than declaring a JS function, and passing knowledge of that function around via the `$OnLoad` global variable to be executed during the `body` element's `load` event, we just execute the function body at the end of the body element. This has the same result.
Where the autofocusing is unconditional, just use the [HTML autofocus attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autofocus) instead of JS.
This removes all usage of the `$OnLoad` global, so we remove that functionality.
=> Clean up setfocus()

include/freshports.php, www/css/freshports.css, www/manifest.json
Some minor cleanups in the <head> tag and site header.
- Remove the MSSmartTags header: I don't think this does anything relevant any more, the references I find to it only are for an unreleased Internet Explorer 6 feature?
- Move the tooltip styles into the global site CSS file (and fix some comment syntax while I'm there)
- The Amazon associate pixel seems to not actually have a valid cert for the `ir-na.amazon-adsystem.com` domain, so I've updated it to `ir-ca.amazon-adsystem.com` for which the cert is valid.
- Not sure if it's used much, but added some more details to the `manifest.json` file for those that want to add FreshPorts to their mobile device homescreen or install it as a PWA.
=> Header Cleanup

classes/user.php, include/constants.php, include/freshports.php, include/getvalues.php, www/backend/announcements.php, www/bouncing.php, www/customize.php, www/delete-account.php, www/filter-setup.php, www/login.php, www/logout.php, www/pkg_upload.php, www/port-watch.php, www/ports-new.php, www/report-subscriptions.php, www/watch-categories.php, www/watch-list-maintenance.php, www/watch.php
Per mention in #249, some updates to how the user ID cookie is handled.
I considered switching to a hmac-signed value or something for token generation, but since we don't store actual data in the token I don't think it would be much of an improvement in security beyond just being an even longer value to guess. So I've just made it use a better source of entropy to theoretically make it harder to guess. I'm not an expert in security but I think what we have is actually OK.
FreshPorts doesn't access the cookie from JS anywhere I can see, so it's made HTTPOnly to reduce the risk from XSS attacks accessing user tokens. If the site is served over HTTPS I've made it so the cookies are only sent in that way going forward. I've set the samesite attribute explicitly to the modern default, `Lax` …
=> Cookie Attribute Updates

include/constants.php, include/freshports.php, www/customize.php, www/login.php, www/new-user.php
This makes password hashing configurable via `constants.php`, then switches that config to using bcrypt for password hash storage rather than md5 for new users and users updating their passwords. bcrypt isn't perfect but is a significant improvement for no additional dependencies.
The cost may need tweaking depending on the DB server's hardware/load.
=> Password Storage Improvements

www/css/freshports.css
These styles are different from prod on the package status table in a port details page.
See:
https://devgit.freshports.org/graphics/darktable/#packages
vs
https://www.freshports.org/graphics/darktable/#packages
=> Remove incorrectly merged stylesheet for div.scrollmenu

include/freshports.php, www/css/freshports.css
- Fixes the additional padding mentioned in [258](https://github.com/FreshPorts/freshports/pull/258#issuecomment-832344140).
- Last cleanup for the sidebar, not counting included HTML tables
- Cleanup for the footer (also properly centered now, let me know if you want the gaps at the sides removed)
- [Attached is the diff ](https://github.com/FreshPorts/freshports/files/6425958/vuln-latest.diff.txt) for the new output for the `vuln-latest.html` file; basically drops any `align` and `nowrap` attributes, and swaps the `width` of the `table` for the `fullwidth` class
=> HTML Cleanup: Sidebar Vulnerability list & Footer

rewrite/functions.php, rewrite/missing-category.php, rewrite/missing-non-port.php, rewrite/missing-port.php, rewrite/missing.php, www/--/index.php
Bit of a refactor of the logic used to route 404 URIs to detect the page to take the user to.
- Mostly consolidating branches so there's a bit less state to keep track of; the only big state now is for categories; ports and other elements are handled as they are encountered
- Removal of some redundant wrapping functions
- I think this fixes some issues with the existing implementation:
- 301s to fix case sensitivity issues previously didn't work because the check only happened after succeeding on a case sensitive search; so it would always match (so e.g. https://www.freshports.org/www/DENO/ is "missing", rather than redirecting ala https://a.freshports.org/www/DENO/ ) (I'm not familiar enough with the prepared statements used here to know if the case-insensitive search will have much of a …
=> Rewrite Cleanup

classes/port-display.php, include/freshports.php, include/watch-lists.php, rewrite/functions.php, rewrite/missing-category.php, rewrite/missing-non-port.php, rewrite/missing-port.php, rewrite/missing.php, www/--/index.php, www/css/freshports.css
Follows from #277 
Cleans up deprecated HTML attributes/elements in use on port pages (e.g. https://www.freshports.org/devel/py-buildbot/)
Mostly align, valign, width attributes and some of the b elements.
Still a handful of public pages that need more work to be valid HTML5, but we're getting there. More PRs to come, then there'll be one to switch the doctype and resync the styles with non-quirks stylesheets.
Please let me know if there are any issues!
=> HTML Cleanup: Port pages

classes/files-display.php, classes/port-display.php, include/ads-burst-media.php, include/burstmedia.php, include/freshports.php, include/freshports_page.php, rewrite/functions.php, www/backend/newsfeeds.php, www/commit.php, www/css/freshports.css, www/faq.php, www/fp2-announcement.php, www/index.php, www/inthenews.php, www/legal.php, www/now-in-maintenance-mode.php, www/release-2004-10.php, www/search.php, www/vuxml.php, www/watch-list.php
Builds off #281.
This makes most of the remaining public pages that don't require a login use valid HTML5 markup.
Todo:
- pages that require a login
- vuxml: This doesn't have a stylesheet at the moment, not sure how much we should change it?
- Switch to HTML5 doctype and resync stylesheets with non-quirksmode defaults
=> HTML Cleanup: public pages

classes/port-display.php, www/css/freshports.css
Rather than relying on the title attribute, show the timestamp information directly in CSS when in the :hover state. This removes the delay where you have to 'linger' on the cell to get it to appear so should make this feature easier to discover.
For touch devices, also show it on :focus, and you can now click on the cells to keep the information visible; this is also better for certain classes of accessibility since you don't need to keep the pointer still to see the content. As a bonus if you _do_ have a pointer, you can use this to compare the value of multiple cells a bit more easily. That you can click the cells isn't very discoverable, though, but that's a bit more challenging to solve without actually just saying as much.
The new tooltip is very basic and pretty ugly, but we can …
=> Packages table: CSS tooltip

include/new-user.php, include/spam-filter-information.php, include/watch-lists.php, www/backend/watch-list.php, www/css/freshports.css, www/customize.php, www/new-user.php, www/pkg_process.inc, www/pkg_upload.php, www/report-subscriptions.php, www/watch-categories.php, www/watch-list-maintenance.php, www/watch.php
- HTML5 validation fixes for the major remaining pages that are only accessible with an account (mostly watch-list and account related pages)
- Unnest some tables
- Add some HTML labels to forms
- Tweak some HTML form validation
- Make the watch-list RSS feed page use the normal site template
=> HTML Cleanup: User-specific pages

configuration/virtualhost-common.conf.sample
Suggest the use of gzip compression for text-like content types in the nginx config. This would reduce bandwidth and improve download time/page performance for most users.
Similarly, suggest long cache lifetimes for the:
- CSS file (which is decorated with a content hash so should never go stale)
- images (which are largely static or easily updated to new paths)
- Javascript libs (which are static copies of upstream libs, which we could easily identify by version if needed).
E.g. compressing the HTML returned from requesting the homepage can reduce the filesize from 188KB down to ~25KB (GZIP level 6), ~15% of the original size.
=> nginx: Add sample config for compression and asset caching

configuration/virtualhost-common-ssl.conf.sample
Follow on from #290, it [looks like](https://www.webpagetest.org/result/210524_BiDcDM_c5e2747c9b6da59344ee2cc07029c9fa/1/details/#waterfall_step1) a big chunk (up to 40% for a fresh connection that needs to include DNS lookup) of our Time to First Byte is spent on the OCSP verification of the Let's Encrypt cert.
This PR adds required nginx config to enable [OCSP stapling](https://en.wikipedia.org/wiki/OCSP_stapling), which would prevent users needing to do this additional check to validate the certificate and load the site faster.
This similarly to #290 just updates the sample configs, but would be good to see the update migrated to the real configs dev/test and eventually prod.
=> nginx: Add sample config for OCSP stapling

classes/port-display.php, www/commit.php, www/css/freshports.css
- Fixes some validation errors introduced in the fix for #287
- Improve HTML semantics in pkg install instructions (kbd over code elements)
- Fixes commit.php page rendering when given an invalid `message_id`  (fixes #204) (also should fix #193 when combined with #292)
- Clean up old announcement handling
=> HTML Fixes: package flavors and invalid message ID

include/freshports.php
This disables nginx's page buffering when rendering HTML pages using `freshports_Start`; at the end of that call we then flush the buffers to the user so the browser can start parsing HTML earlier and downloading assets like the CSS and the site banner. This gives it something to do while we do the real work talking to the database and constructing the rest of the page.
This seems to consistently shave about 300ms off our TTFB metric on my environment, and should get most of the front-end assets loading earlier and potentially improve our First Contentful Paint (FCP) metrics by loading the header + banner of the page. FCP is considered a Core Web Vital and should improve our SEO.
=> TTFB optimization

include/freshports.php, www/css/freshports.css
Add a general mechanism for holiday-specific CSS decorations. 
- Adds holiday definition for LGBTQ+ Pride Month
The holiday definitions are date-based, so it should switch back to normal automatically once July rolls around.
TODO: Migrate the existing Remembrance Day decorations to display using this method, if possible.
For the LGBTQ+ Pride month colours, I went with the 2017 Gilbert Baker 9-band variant of the [Rainbow Flag](https://en.wikipedia.org/wiki/Rainbow_flag_(LGBT)) (which adds lavender to symbolise Diversity). This seems to be most in-tune with the modern and popular "Philadelphia" and "Progress Pride" variants while still keeping the purely band-based motif. I'm not really part of these communities, though, so very open to advice if we want to use another variant or just …
=> Generalize holiday detection support

classes/port-display.php
Oh.  matches is needed. Let's supply that
fixes #216 again
=> Properly display the package name with python prefixes.

www/css/freshports.css
Fixes #330
Looks a bit chalky to me, but the contrast ratio is higher for sure, which should be more accessible and thus better and hopefully reads easier.
I think I based the original scheme off adjusted values from Firefox's Reader Mode dark stylesheet, thinking it'd be a good enough base.
=> Adjust dark mode contrast

www/css/freshports.css
Fixes #320.
Considered being more selective to only impact the hashes in distinfo, but then decided not breaking the site layout was more important than occasionally wrapping text too often.
=> Adjust text wrapping for pre-like elements

classes/newsfeed.php
Should fix #354
Move the branch filtering logic earlier in the query; Old behavior finds the latest 100 commits that touch ports, which probably are for `head` (rather than the branch we're looking for) and so they get filtered by checking the branch later, resulting in empty results.
This makes it only look for commits that touch ports that are also on the target branch, to get the desired behavior. This should fix feeds for all historical branches, but nonexistent/new branches are now slow as it churns through history looking for 100 commits on that branch name. I'm relying on the caching to make this not a DOS threat. `head` branch should behave the same as it does now.
E.g.
Current: https://www.freshports.org/backend/html.php?branch=2021Q1
vs
Patched: …
=> Fix newsfeeds for branches

www/faq.php
Re: <https://github.com/FreshPorts/freshports/issues/384#issuecomment-1257279011> it's not possible to distinguish between fallout and a skip, so offer an explanation for there being no fallout in response to a click on the fallout icon.
=> faq.php: some fallout lists will be empty

classes/port-display.php, include/constants.php, include/freshports.php
The last subversion commit was on 2022-10-25 18:42:09
If the port was added before that date, it has subversion history. Otherwise, display a greyed-out subversion icon.
re: https://github.com/FreshPorts/freshports/issues/403
=> Display a greyed subversion icon if no subversion history

classes/display_commit.php, www/css/freshports.css
Many of the icons/badges are available on the ports page - let's limit those links to that page. e.g. The links to different repos.
re: #506
=> After changing the UI, let's revert some of it.

classes/port-display.php
Sometimes there are no packages available for a port. That may be because the build is failing for that port. Provide the fallout link here.
re: #570
classes/port-display.php# On branch 570-no-package-information-for-editorsvscode
=> classes/port-display.php: if no packages for this port, suggest fallout

classes/port-display.php
classes/port-display.php: Extend dependency line to consider PYTHON_PKGNAMESUFFIX
The code already does:
${PYTHON_PKGNAMEPREFIX}poetry-core>0:devel/py-poetry-core@${PY_FLAVOR}
Now it also caters for:
pylint${PYTHON_PKGNAMESUFFIX}>0:devel/pylint
=> 578 fix python prefix issues arsing out of python 311 what about suffixes

include/freshports.php, www/opensearch.php
This pull request adds [OpenSearch](https://en.wikipedia.org/wiki/OpenSearch) support, providing an easy way for users to add FreshPorts as a search engine to their browser[^1].
[^1]: Or in case of Firefox, allowing them to add it at all, as the ability to define custom search engines was removed.
=> OpenSearch support
