configuration/robots.txt
configuration/virtualhost-common-ssl.conf
include/constants.local.php
include/freshports.php
www/backend/news.php
www/css/freshports.css

Ronaldklop master

---

www/backend/news.php

I don't know what I was thinking in the first try. :-)

Fix the calculation of the quarter of the year.

---

include/freshports.php

This is a follow-up to #108.
The regular expression is expecting to match a single line in a multi-line string.

Add a m modifier to PR regexp

---

classes/user.php
include/freshports.php
include/new-user.php
www/backend/announcements.php
www/bouncing.php
www/customize.php
www/delete-account.php
www/filter-setup.php
www/graphs.php
www/login.php
www/new-user.php
www/password-reset-via-token.php
www/port-watch.php
www/release-2003-04-29.php
www/watch-categories.php

fixes #139
Allow the user to delete their account.
While here, remove references to 'the forum' which is long gone.
Refer to 'account settings' instead of cutomize.

Allow for account deletion

---

classes/newsfeed.php
classes/port-display.php
include/constants.php

Python pkgnameprefix

---

www/generate_content.php
www/graphs2.php
www/javascript/jquery.canvaswrapper.js
www/javascript/jquery.colorhelpers.js
www/javascript/jquery.flot.browser.js
www/javascript/jquery.flot.drawSeries.js
www/javascript/jquery.flot.js
www/javascript/jquery.flot.saturated.js
www/javascript/jquery.flot.uiConstants.js

Reading the FreeBSD Quaterly status report I have decided to take a look at the reported graph issue. Here are my findings:
* first it imports more than just the core of flot plugin
* fixes for PHP code to return conformant JSON data, otherwise newer jQuery will silently bail out
* make use of the aforementioned changes.
I was able to confirm on a hand crafted test env with static snapshots, that the non bar graphs load fine.

Fix graphing of changes

---

www/faq.php

`<a id="anchors">` and more, to complement https://github.com/FreshPorts/freshports/commit/9572b879e71964ad18a674a9130373c122fe7b5b 
`#message` is effective; `#pkg-message` is not. 
Re: `id` in lieu of `name`: <https://www.w3.org/TR/html401/struct/links.html> and answers to <https://stackoverflow.com/q/484719/38108> – I hope I understand correctly.

FAQ: add/modify anchors, and a terser section about anchors

---

classes/newsfeed.php
include/freshports.php
www/backend/index.php

Jethron jethron rss validation

---

www/css/freshports.css
www/generate_content.php
www/graphs.php
www/graphs2.php
www/javascript/freshports.js
www/javascript/graphs.js
www/javascript/jquery.flot.time.js

- Bit of HTML cleanup for the graphs.php and graphs2.php pages
- Rewrite the graphs2 JS and fix some issues (inc #203)
- Clean up some manual serialization code
There might be better options for the charts these days; the flot libs we're using here are pretty out of date also and could at least use an update. I'll do that in a followup PR if nobody beats me to it.
Leaving the note about the graphs being broken until the interactivity is properly restored, though I think this is getting closer to working order.

HTML Cleanup: Graphs

---

www/css/freshports.css
www/generate_content.php
www/graphs2.php
www/javascript/graphs.js

Missed something while making a PR at 1AM, big shock. 😜 
- Missed a valign attribute, now removed
- Fix the datasource format for the `getCommitsOverTime()` graph
- Small CSS tweaks
- Comment some of the JS code because everyone loves comments
- Delete some flot options that don't do anything and are thus confusing
Apart from what's fixed here, #273 looks good to me in dev/test, but shouldn't go ahead without this fix for getCommitsOverTime.

#273 Graphs fixes

---

classes/port-display.php
include/freshports.php
rewrite/functions.php

Fix some regressions in #277 and correct some missed corner cases from #278 
Also some additional HTML fixes. Tested many more port pages this time, all passing validation now.

Rewrite + Ports HTML Fixes

---

classes/port-display.php
www/css/freshports.css

See #280. 
Inverts the contrast on hover (text becomes white as the background becomes dark), and re-orders the timestamps in the tooltip.

Package interaction

---

include/ads-burst-media.php
include/ads-google-adsense.php
include/ads-phppgads.php
include/ads.php
include/adsense.php
include/burstmedia.php
include/constants.php
include/freshports.php
rewrite/missing-port.php
www/css/freshports.css
www/index.php
www/search.php

There's a few visual changes, mostly whitespace where I couldn't easily replicate the quirks stylesheet correctly. But otherwise I think it's pretty close, and [we're valid HTML5](https://validator.w3.org/nu/?doc=https%3A%2F%2Fa.freshports.org%2F) for most public pages after this.
Still todo are the pages that require a login (my environment is in maintenance mode so I need to change that and create a user to get to those pages and verify).
But with this is in place we'll be able to use all the new element types and hopefully start removing some of the nested tables used for layout.

Switch to HTML5

---

www/commit.php

Mostly some housekeeping, should also fix #237. Largely whitespace changes, though.

commit.php cleanup

---

www/css/freshports.css

- Add initial work to support a dark theme
- Remove the repetition of the Pride Month decoration to look more flag-like
Decent start towards #304, slightly alleviates #305

Support prefers-color-scheme: dark

---

classes/port-display.php

Fetch, patch, extract dependencies weren't taken into account.

Take into account all dependencies when deciding that there are no dependencies

---

classes/ports_by_uses.php
www/faq.php
www/search.php

225 new feature search by uses=

---

www/search.php

fixes https://github.com/FreshPorts/freshports/issues/425

Fix logic error so plain text searches produce output

---

classes/port-display.php
www/css/freshports.css

re: https://github.com/FreshPorts/freshports/issues/424

When there is no maintainer, hightlight that.

---

docs/404-for-virtual-pages.php
include/freshports.php
www/backend/announcements.php
www/backend/status.php
www/category-maintenance.php
www/css/freshports.css
www/index.php
www/vuxml.php
www/watch.php

Implementing the changes from #439

Orangecms cellpadding

---

classes/port-display.php
classes/ports-unrefreshed.php
classes/ports.php
classes/user.php
include/constants.php
rewrite/functions.php
rewrite/missing-category.php
rewrite/missing-port.php
rewrite/new-url-parsing.php
www/--/new-url-parsing.php
www/new-user.php
www/port-watch.php
www/search.php

New url parsing

---

classes/port-display.php
include/freshports.php

Properly calculate the date of the first quarter.

---

www/search.php

When sorting, use the correct sort field and ordering

---

classes/port-display.php

Do not display conflict matches - they are not populated

---

classes/ports.php

re: https://github.com/FreshPorts/freshports/issues/576

Allow child classes access to $Debug

---

classes/port-display.php

re: https://github.com/FreshPorts/freshports/issues/582

Add support for PHP_PKGNAME{PREFIX,SUFFIX}

---

www/opensearch.php

Echo XML declaration for compatibility with PHP's [short open tag option](https://www.php.net/manual/en/ini.core.php#ini.short-open-tag).

www/opensearch.php: Echo XML declaration

---

www/faq.php

Nits, including ABIs (plural of ABI).
Make a separate paragraph from the two sentences about no quarterly for CURRENT.

faq.php: typos etc.

---

www/faq.php

One question mark instead of two.
A few other suggestions.

faq.php: ABIs: minor changes

---

www/backend/index.php

* https://www.freshports.org/backend/newsfeeds.php
* https://www.freshports.org/backend/
re # 621

Merge two urls into one:
